name: 'Process New Grant Application'
description: 'Processes a new grant application by applying configured labels, assignments and notifications'

inputs:
  github-token:
    description: 'GitHub token with necessary permissions'
    required: true
  vars:
    description: 'GitHub Variables containing workflow configuration'
    required: true
  event:
    description: 'GitHub event that triggered the workflow'
    required: true

runs:
  using: "composite"
  steps:
