name: Grant Application Workflow

on:
  issues:
    types: [labeled, unlabeled]

permissions:
  issues: write

jobs:
  process-grant-application:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate-token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{ vars.ADMIN_APP_ID }}
          private_key: ${{ secrets.ADMIN_APP_PRIVATE_KEY }}
          installation_retrieval_mode: id
          installation_retrieval_payload: ${{ vars.ADMIN_APP_INSTALLATION_ID }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Get Issue "Status" for All Projects
        id: get-status-list
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        uses: octokit/graphql-action@v2.x
        with:
          query: |
            query GetIssueStatus($issueId: ID!) {
                node(id: $issueId) {
                  ... on Issue {
                    projectItems(first: 10) {
                      nodes {
                        fieldValueByName(name: "Status") {
                          ... on ProjectV2ItemFieldSingleSelectValue {
                            field {
                              ... on ProjectV2Field {
                                id
                                name
                              }
                            }
                            name
                          }
                        }
                      }
                    }
                  }
                }
              }
          variables: |
            issueId: ${{ github.event.issue.node_id }}

      - name: Get Grant Application Status
        id: get-grant-application-status
        if: ${{steps.get-status-list.outputs.data}}
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          script: |
            const projectItems = ${{ steps.get-status-list.outputs.data }};
            const filteredProjectItems = projectItems.filter(item =>  
              item.fieldValueByName.field.id === statusId
            );

            if(filteredProjectItems.length == 0) {
              core.info('Grant Application status not found for ${{ github.event.issue.id }}: (vars.PROJECT_GRANT_APPLICATION_PROJECT_ID: "${{ vars.PROJECT_GRANT_APPLICATION_PROJECT_ID }}")');
              core.setOutput('result', "New");
            } else {
              core.setOutput('result', filteredProjectItems[0].fieldValueByName.name);
            }

      - name: Add Issue to GitHub Project
        id: add-to-project
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        if: steps.get-status.outputs.isInProject == 'false'
        uses: octokit/graphql-action@v2.x
        with:
          query: |
            mutation AddIssueToProject($project_id: ID!, $content_id: ID!) {
              addProjectV2ItemById(input: { projectId: $project_id, contentId: $content_id }) {
                item {
                  id
                }
              }
            }
          variables: |
            project_id: ${{vars.PROJECT_GRANT_APPLICATION_PROJECT_ID}}
            content_id: ${{ github.event.issue.id }}

      - name: 'Add Issue to GitHub Project": Set Status to "New"'
        id: new-issue-status
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        if: steps.add-to-project.outcome == 'success'
        uses: octokit/graphql-action@v2.x
        with:
          query: |
            mutation UpdateProjectV2ItemFieldValue(
              $project_id: ID!
              $status_id: ID!
              $item_id: ID!
              $value: String!
            ) {
              updateProjectV2ItemFieldValue(
                input: {
                  projectId: $project_id
                  fieldId: $status_id
                  itemId: $item_id
                  value: { 
                    singleSelectOptionId: $value
                  }
                }
              ) {
                projectV2Item {
                  id
                }
              }
            }
          variables: |
            {
              "project_id": "${{ vars.PROJECT_GRANT_APPLICATION_PROJECT_ID }}",
              "status_id": "${{ vars.PROJECT_GRANT_APPLICATION_STATUS_FIELD_ID }}",
              "item_id": "${{ steps.add-to-project.outputs.result.item.id }}",
              "value": ${{vars.PROJECT_GRANT_APPLICATION_STATUS_NEW_ID}}
            }

      - name: Get all current labels
        id: get-labels
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        uses: actions/github-script@v7
        with:
          script: |
            const { data: labels } = await github.rest.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              headers: {
                authorization: `token ${{ steps.generate-token.outputs.token }}`
              }
            });
            core.setOutput('result', JSON.stringify(labels.map(label => label.name)));



      - name: Process New Status
        if: steps.get-grant-application-status.outputs.result == 'New'
        uses: ./.github/actions/grant-application/new
        with:
          token: ${{ steps.generate-token.outputs.token }}
          issue-number: ${{ github.event.issue.number }}
          issue-title: ${{ github.event.issue.title }}
          label-name: ${{ github.event.label.name }}
          label-action: ${{ github.event.action }}
          current-labels: ${{ steps.get-labels.outputs.result }}
          vars: ${{ vars }}
          nerdgguy-app-id: ${{ secrets.NERDGGUY_APP_ID }}
          nerdgguy-client-id: ${{ secrets.NERDGGUY_CLIENT_ID }}
          nerdgguy-installation-id: ${{ secrets.NERDGGUY_INSTALLATION_ID }}
          
      - name: Process Under Review Status
        if: steps.get-grant-application-status.outputs.result == 'Under Review' 
        uses: ./.github/actions/grant-application/under-review
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          issue-title: ${{ github.event.issue.title }}
          label-name: ${{ github.event.label.name }}
          label-action: ${{ github.event.action }}
          current-labels: ${{ steps.get-labels.outputs.result }}
          vars: ${{ vars }}
